"""Added Torrent.time_added

Revision ID: 4b1f175f02f3
Revises: 453c8dff2523
Create Date: 2022-11-21 17:58:31.331532-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1f175f02f3'
down_revision = '453c8dff2523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrents', sa.Column('time_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('torrents', 'time_added')
    # ### end Alembic commands ###
