"""Added Torrent

Revision ID: 453c8dff2523
Revises: 
Create Date: 2022-11-18 19:22:17.814307-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453c8dff2523'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('state', sa.Enum('DL', 'SEED', 'PEND', 'CHECK', 'E', 'Q', 'ALLOC', 'MOV', name='statechoices'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torrent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('torrents')
    # ### end Alembic commands ###
