"""Add TorrentSnapshot

Revision ID: 475a0bc646c1
Revises: 4b1f175f02f3
Create Date: 2022-11-21 19:27:28.643465-05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475a0bc646c1'
down_revision = '4b1f175f02f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrent_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=True),
    sa.Column('total_uploaded', sa.Integer(), nullable=True),
    sa.Column('total_seeds', sa.Integer(), nullable=True),
    sa.Column('total_peers', sa.Integer(), nullable=True),
    sa.Column('time_recorded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('torrents', sa.Column('next_check_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('torrents', 'next_check_time')
    op.drop_table('torrent_snapshots')
    # ### end Alembic commands ###
